replicaCount: 1

image:
  # Helm chart: https://github.com/kyverno/kyverno/blob/<RELEASE>/charts/kyverno/values.yaml
  # Note: Replace <RELEASE> by the target release version in the above URL
  registry: ghcr.io
  repository: kyverno/kyverno
  tag: 'v1.9.1'

resources:
  limits:
    cpu: 1
    memory: 700Mi
  requests:
    cpu: 100m
    memory: 400Mi

initImage:
  # Helm chart: https://github.com/kyverno/kyverno/blob/<RELEASE>/charts/kyverno/values.yaml
  # Note: Replace <RELEASE> by the target release version in the above URL
  registry: ghcr.io
  repository: kyverno/kyvernopre
  tag: 'v1.9.1'

testImage:
  # Helm chart: https://github.com/kyverno/kyverno/blob/<RELEASE>/charts/kyverno/values.yaml
  # Note: Replace <RELEASE> by the target release version in the above URL
  registry: docker.io
  repository: library/busybox
  tag: '1.36.0'

config:
  webhooks:
  # not used if auto-generation of admission webhook configs is disabled
  - namespaceSelector:
      matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn
        values:
        - kube-system

# Disable auto-generation of admission webhook configs, because resource matching
# is too imprecise and therefore Gardener's shoot hibernation gets stuck.
extraArgs:
# default values from chart
- --loggingFormat=text
- --exceptionNamespace=kyverno
# added
- --autoUpdateWebhooks=false

webhooksCleanup:
  enable: true
  # pre-delete hook does use image pull secrets, therefore it cannot use
  # our mirror repo
  #image: concise.common.repositories.cloud.sap/mirror-linux-amd64/docker.io/bitnami/kubectl:1.26.2@sha256:b10b4ae540643a98ce40333391cac6328eb77de078508c39b9644db6645d3e33

serviceMonitor:
  enabled: true

cleanupController:
  enabled: false
  image:
    # Helm chart: https://github.com/kyverno/kyverno/blob/<RELEASE>/charts/kyverno/values.yaml
    # Note: Replace <RELEASE> by the target release version in the above URL
    registry: ghcr.io
    repository: kyverno/cleanup-controller
    tag: 'v1.9.1'
